task_manager/labels/urls.py
from django.urls import path
from task_manager.labels import views

urlpatterns = [
    path('', views.LabelPageView.as_view(), name='labels'),
    path('create/', views.LabelCreatePageView.as_view(), name='label_create'),
    path(
        '<int:pk>/update/',
        views.LabelUpdatePageView.as_view(),
        name='label_update'),
    path(
        '<int:pk>/delete/',
        views.LabelDeletePageView.as_view(),
        name='label_delete'
     ),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views

urlpatterns = [
    path('', views.TaskPageView.as_view(), name='tasks'),
    path('create/', views.TaskCreatePageView.as_view(), name='task_create'),
    path('<int:pk>/', views.TaskShowPageView.as_view(), name='task_show'),
    path(
        '<int:pk>/update/',
        views.TaskUpdatePageView.as_view(),
        name='task_update'
     ),
    path(
        '<int:pk>/delete/',
        views.TaskDeletePageView.as_view(),
        name='task_delete'
     ),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from task_manager.views import HomePageView
from task_manager.users.views import UserLoginView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('tasks/', include('task_manager.tasks.urls'), name='tasks'),
    path('users/', include('task_manager.users.urls'), name='users'),
    path('statuses/', include('task_manager.statuses.urls'), name='statuses'),
    path('labels/', include('task_manager.labels.urls'), name='labels'),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

urlpatterns = [
    path('', views.UserPageView.as_view(), name='users'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('create/', views.UserCreatePageView.as_view(), name='users_create'),
    path(
        '<int:pk>/update/',
        views.UserUpdatePageView.as_view(),
        name='users_update'
     ),
    path(
        '<int:pk>/delete/',
        views.UserDeletePageView.as_view(),
        name='users_delete'
     ),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.conf import settings
from django.db import models
from task_manager.statuses.models import Status
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(max_length=150)
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        related_name='tasks',
    )
    labels = models.ManyToManyField(
        Label,
        blank=True,
        related_name='tasks',
    )
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_tasks'
    )
    executor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='responsible_tasks'
    )
    description = models.TextField(blank=True)
    
    def __str__(self):
        return self.description

task_manager/users/models.py
from django.contrib.auth.models import User as DjangoUser


class User(DjangoUser):

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

task_manager/labels/forms.py
from django import forms
from task_manager.labels.models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ['name']
        labels = {
            'name': 'Имя',
        }

task_manager/statuses/forms.py
from django import forms
from task_manager.statuses.models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']
        labels = {
            'name': 'Имя',
        }

task_manager/tasks/forms.py
from django import forms
from task_manager.tasks.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'name', 
            'status',
            'labels',
            'creator',
            'executor',
            'description'
        ]
        labels = {
            'name': 'Имя',
            'description': 'Описание',
            'status': 'Статус',
            'executor': 'Исполнитель', 
            'labels': 'Метки',
        }
        widgets = {
            'description': forms.Textarea(attrs={'placeholder': ''}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # The function which is called to show executor in the form
        self.fields['executor'].label_from_instance = (
            lambda obj: f'{obj.first_name} {obj.last_name}'
        )

task_manager/common/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import \
    ListView, CreateView, UpdateView, DeleteView


class BaseListView(ListView):
    context_object_name = 'table_content'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(getattr(self, 'context_extra', {}))
        return context


class BaseCreateView(CreateView):
    template_name = 'create.html'
    
    def form_valid(self, form):
        message_ = self.messages_show.get('success', '')
        messages.success(
            self.request,
            f'{message_}: {form.instance.name}',
            extra_tags='.alert',
        )
        return super().form_valid(form)
    
    def form_invalid(self, form):
        message_ = self.messages_show.get('error', '')
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(
                    self.request,
                    f'{message_}: {field}: {error}',
                    extra_tags='.alert',
                )
        return redirect(self.success_url)


class BaseUpdateView(UpdateView):
    template_name = 'update.html'
    
    def form_valid(self, form):
        messages.success(
            self.request,
            self.messages_show.get(
                'success',
                'BaseUpdateView success'
            ),
            extra_tags='.alert',
        )
        return super().form_valid(form)


class BaseDeleteView(DeleteView):
    template_name = 'delete.html'
    
    def has_related_objects(self):
        # Метод переписывается в дочерних классах
        return False
        
    def post(self, request, *args, **kwargs):        
        if self.has_related_objects():
            messages.error(
                self.request,
                self.messages_show.get(
                    'error',
                    'BaseDeleteView error'
                ),
                extra_tags='.alert',
            )
            return redirect(self.success_url)
        
        response = super().post(request, *args, **kwargs)
        messages.success(
            self.request,
            self.messages_show.get(
                'success',
                'BaseDeleteView success'
            ),
            extra_tags='.alert',
        )
        return response

task_manager/labels/views.py
from task_manager.common.views import \
    BaseListView, BaseCreateView, BaseUpdateView, BaseDeleteView
from task_manager.labels.models import Label
from task_manager.labels.mixins import LabelFormMixin
from task_manager.common.messages import LABEL_MESSAGES
from django.urls import reverse_lazy
import logging

logger = logging.getLogger(__name__)


class LabelPageView(LabelFormMixin, BaseListView):
    template_name = 'labels/index_labels.html'
    context_extra = {
        'title': 'Labels',
        'table_headers': ['ID', 'Метка', 'Действия'],
        'form_action': 'label_create',
        'button_create': 'Создать метку',
    }


class LabelCreatePageView(LabelFormMixin, BaseCreateView):
    success_url = reverse_lazy('labels')
    context_extra = {
        'header': 'Labels',
        'button': 'Создать',
    }
    messages_show = {
        'error': LABEL_MESSAGES['create_error'],
        'success': LABEL_MESSAGES['create'],
    }


class LabelUpdatePageView(LabelFormMixin, BaseUpdateView):
    success_url = reverse_lazy('labels')
    messages_show = {
        'success': LABEL_MESSAGES['update'],
    }


class LabelDeletePageView(BaseDeleteView):
    model = Label
    success_url = reverse_lazy('labels')
    context_extra = {
        'header': 'Labels',
        'fields_names': ['ID', 'name'],
    }
    messages_show = {
        'error': LABEL_MESSAGES['delete_error'],
        'success': LABEL_MESSAGES['delete'],
    }
    
    def has_related_objects(self):
        return self.get_object().tasks.exists()
    
    def dispatch(self, request, *args, **kwargs):
        logger.info(f'{request.user} in LabelDeletePageView dispatch')
        return super().dispatch(request, *args, **kwargs)

task_manager/statuses/views.py
from task_manager.common.views import \
    BaseListView, BaseCreateView, BaseUpdateView, BaseDeleteView
from task_manager.statuses.models import Status
from task_manager.statuses.mixins import StatusFormMixin
from task_manager.tasks.models import Task
from task_manager.common.messages import STATUS_MESSAGES
from django.urls import reverse_lazy
import logging

logger = logging.getLogger(__name__)


class StatusPageView(StatusFormMixin, BaseListView):
    template_name = 'statuses/index_statuses.html'
    context_extra = {
        'title': 'Statuses',
        'table_headers': ['ID', 'Status', 'Actions'],
        'form_action': 'status_create',
        'button_create': 'Создать статус',
    }


class StatusCreatePageView(StatusFormMixin, BaseCreateView):
    success_url = reverse_lazy('statuses')
    context_extra = {
        'header': 'Statuses',
        'button': 'Создать',
    }
    messages_show = {
        'error': STATUS_MESSAGES['create_error'],
        'success': STATUS_MESSAGES['create'],
    }


class StatusUpdatePageView(StatusFormMixin, BaseUpdateView):
    success_url = reverse_lazy('statuses')
    messages_show = {
        'success': STATUS_MESSAGES['update'],
    }


class StatusDeletePageView(BaseDeleteView):
    model = Status
    success_url = reverse_lazy('statuses')
    context_extra = {
        'header': 'Statuses',
        'fields_names': ['ID', 'name'],
    }
    messages_show = {
        'error': STATUS_MESSAGES['delete_error'],
        'success': STATUS_MESSAGES['delete'],
    }
    
    def has_related_objects(self):
        return Task.objects.filter(status=self.get_object()).exists()
    
    def dispatch(self, request, *args, **kwargs):
        logger.info(f'{request.user} in StatusDeletePageView dispatch')
        return super().dispatch(request, *args, **kwargs)

task_manager/tasks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import \
    UpdateView, DeleteView, CreateView, DetailView
from django.urls import reverse_lazy
from django_filters.views import FilterView
from task_manager.tasks.models import Task
from task_manager.tasks.mixins import TaskFormMixin
from task_manager.tasks.filters import TaskFilter
from task_manager.common.messages import TASK_MESSAGES
import logging

logger = logging.getLogger(__name__)


class TaskPageView(LoginRequiredMixin, FilterView, TaskFormMixin):
    template_name = 'tasks/index_tasks.html'
    filterset_class = TaskFilter
    context_extra = {
        'title': 'Tasks',
        'table_headers': [
            'ID',
            'Имя',
            'Статус',
            'Метки',
            'Создатель', 
            'Исполнители',
            'Описания',
            'Действия',
        ],
        'form_action': 'task_create',
        'button_create': 'Создать задачу',
    }

    def get(self, request, *args, **kwargs):
        logger.info(f"\nGET params: {request.GET}")
        return super().get(request, *args, **kwargs)
    
    def get_queryset(self):
        queryset = super().get_queryset()
        filterset = self.filterset_class(
            self.request.GET,
            queryset=queryset,
            request=self.request,
        )
        filtered_qs = filterset.qs
        logger.info(f'Applied filters - \
                    status: {self.request.GET.get("status")}, \
                    labels: {self.request.GET.get("labels")}, \
                    count: {filtered_qs.count()}'
        )
        return filtered_qs


class TaskShowPageView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/show_task.html'
    context_object_name = 'task'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Task Details'
        return context


class TaskCreatePageView(LoginRequiredMixin, TaskFormMixin, CreateView):
    template_name = 'create.html'
    success_url = reverse_lazy('tasks')
    context_extra = {
        'title': 'Tasks',
        'table_headers': [
            'ID',
            'Статус',
            'Метки',
            'Создатель', 
            'Исполнители',
            'Описания',
            'Действия',
        ],
        'form_action': 'task_create',
        'button': 'Создать',
    }
    messages_show = {
        'error': TASK_MESSAGES['create_error'],
        'success': TASK_MESSAGES['create'],
    }
    
    def form_valid(self, form):
        form.instance.creator = self.request.user
        logger.info(f'Creating task when logged in as {self.request.user}')
        messages.success(
            self.request,
            self.messages_show['success'],
            extra_tags='.alert',
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(
                    self.request,
                    f'{self.messages_show["error"]}: {field}: {error}',
                    extra_tags='.alert',
                )
        return redirect('task_create')


class TaskUpdatePageView(LoginRequiredMixin, TaskFormMixin, UpdateView):
    template_name = 'update.html'
    success_url = reverse_lazy('tasks')
    messages_show = {
        'success': TASK_MESSAGES['update'],
    }

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        self.original_description = obj.description
        return obj

    def form_valid(self, form):
        messages.success(
            self.request,
            self.messages_show['success'],
            extra_tags='.alert',
        )
        return super().form_valid(form)


class TaskDeletePageView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('tasks')
    template_name = 'delete.html'
    context_extra = {
        'header': 'Tasks',
        'fields_names': ['ID', 'name'],
    }
    messages_show = {
        'error': TASK_MESSAGES['delete_error'],
        'success': TASK_MESSAGES['delete'],
    }

    def get(self, request, *args, **kwargs):
        object_to_delete = self.get_object()
        if object_to_delete.creator.id != request.user.id:
            logger.info(f'{request.user} CANNOT delete task \
                        created by {object_to_delete.creator}')
            messages.error(
                self.request,
                self.messages_show['error'],
                extra_tags='.alert'
            )
            return redirect(self.success_url)
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        object_to_delete = self.get_object()
        if object_to_delete.creator.id != request.user.id:
            logger.info(f"{request.user} CANNOT delete task \
                        created by {object_to_delete.creator}")
            messages.error(
                self.request,
                self.messages_show['error'],
                extra_tags='.alert'
            )
            return redirect(self.success_url)
        
        response = super().post(request, *args, **kwargs)
        messages.success(
            self.request,
            self.messages_show['success'],
            extra_tags='.alert',
        )
        return response
        
    def dispatch(self, request, *args, **kwargs):
        logger.info(f"{request.user} now in \
                    TaskDeletePageView dispatch method")
        return super(DeleteView, self).dispatch(request, *args, **kwargs)

task_manager/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'

task_manager/templates/tasks/index_tasks.html
{% extends 'index.html' %}
{% load custom_tags %}
{% block title %}{{ title }}{% endblock %}
{% block contents %}
<div class="card mb-3">
    <div class="card-body bg-light">
      <form class="form-inline center" method="get">
        <div class="mb-3">
          <label class="form-label" for="id_status">Статус</label>
          <select name="status" class="form-select" id="id_status">
            <option value="">---------</option>
            {% for status in statuses %}
              <option value="{{ status.id }}" {% if request.GET.status == status.id|stringformat:"s" %}selected{% endif %}>{{ status.name }}</option>
            {% endfor %}
          </select>
        </div>
        
        <div class="mb-3">
          <label class="form-label" for="id_executor">Исполнитель</label>
          <select name="executor" class="form-select" id="id_executor">
            <option value="">---------</option>
            {% for executor in executors %}
              <option value="{{ executor.id }}" {% if request.GET.executor == executor.id|stringformat:"s" %}selected{% endif %}>{{ executor.first_name }} {{ executor.last_name }}</option>
            {% endfor %}
          </select>
        </div>
        
        <div class="mb-3">
          <label class="form-label" for="id_labels">Метка</label>
          <select name="labels" multiple class="form-select" id="id_labels">
            {% for label in labels %}
              <option value="{{ label.id }}" {% if request.GET.labels == label.id|stringformat:"s" %}selected{% endif %}>{{ label.name }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="id_self_tasks" name="self_tasks" value="1"{% if request.GET.self_tasks == "1" %}checked{% endif %}>
          <label class="form-check-label" for="id_self_tasks">Только свои задачи</label>
        </div>
        <input class="btn btn-primary" type="submit" value="Показать">
      </form>
    </div>
  </div>
<thead>
    <tr>
        {% for header in table_headers %}
            <th>{{ header }}</th>
        {% endfor %}
    </tr>
</thead>
{% if filter.qs %}
<tbody>
    {% for task in filter.qs %}
        <tr>
            <td>{{ task.id }}</td>
            <td><a href="{% url 'task_show' task.id %}">{{ task.name }}</a></td>
            <td>{{ task.status }}</td>
            <td>
                {% for label in task.labels.all %}
                {{ label }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </td>
            <td>{{ task.creator.first_name }} {{ task.creator.last_name }}</td>
            <td>{{ task.executor.first_name }} {{ task.executor.last_name }}</td>
            <td>{{ task.description }}</td>
            <td>
            <a href="{% url 'task_update' task.id %}">Изменить</a>
            <a href="{% url 'task_delete' task.id %}">Удалить</a>
            </td>
        </tr>
    {% endfor %}
</tbody>
{% else %}
{% endif %}
{% endblock %}

task_manager/templates/tasks/show_task.html
{% extends 'layout.html' %}
{% load custom_tags %}
{% block title %}{{ title }}{% endblock %}
{% block main %}
<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h3>Task #{{ task.id }}: {{ task.name }}</h3>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 200px">Status</th>
                        <td>{{ task.status }}</td>
                    </tr>
                    <tr>
                        <th>Labels</th>
                        <td>
                            {% for label in task.labels.all %}
                                {{ label }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <th>Автор</th>
                        <td>{{ task.creator.first_name }} {{ task.creator.last_name }}</td>
                    </tr>
                    <tr>
                        <th>Исполнитель</th>
                        <td>{{ task.executor.first_name }} {{ task.executor.last_name }} </td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ task.description }}</td>
                    </tr>
                </tbody>
            </table>
            <div class="mt-3">
                <a href="{% url 'task_update' task.id %}" class="btn btn-primary">Изменить</a>
                <a href="{% url 'task_delete' task.id %}" class="btn btn-danger">Удалить</a>
                <a href="{% url 'tasks' %}" class="btn btn-secondary">Back to Tasks</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}